### ISSUE TITLE
error using node-cache-manager-s3

### ISSUE THREAD

**Issue by yagobski** [tprobinson/node-cache-manager-s3#1]
hi i have this error when i use this module with prerender

`2018-12-23T02:15:10.008Z TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
0|server   |     at Function.Buffer.from (buffer.js:183:11)
0|server   |     at S3Cache.set (/home/ubuntu/node_modules/cache-manager-s3/src/index.js:439:33)
0|server   |     at PrerenderCacheManager.saveToCache (/home/ubuntu/node_modules/prerender-cache-manager-glue/index.js:45:14)
0|server   |     at PrerenderCacheManager.beforeSend (/home/ubuntu/node_modules/prerender-cache-manager-glue/index.js:66:15)
0|server   |     at next (/home/ubuntu/node_modules/prerender/lib/server.js:333:13)
0|server   |     at Promise (/home/ubuntu/node_modules/prerender/lib/server.js:344:3)
0|server   |     at new Promise (<anonymous>)
0|server   |     at Object.server.firePluginEvent (/home/ubuntu/node_modules/prerender/lib/server.js:303:9)
0|server   |     at Object.server.finish (/home/ubuntu/node_modules/prerender/lib/server.js:292:7)
0|server   |     at firePluginEvent.then.then.then.then.then.then.then.then.catch (/home/ubuntu/node_modules/prerender/lib/server.js:269:8)
`

**Comment by tprobinson** [comment]
Sorry that it took me so long to get to this! I believe that error occurs when Prerender returns a blank response. Are you still getting this issue?
